[package]
name = "txtdot"
version = "2.0.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
base64 = "0.22.1"
dalet = { version = "1.0.0-pre.34", features = ["types"], default-features = false }
drova_plugins = "3.3.1"
drova_sdk = "3.3.0"
dotenvy = "0.15.7"
image = { version = "0.25.10", default-features = false, features = ["avif", "jpeg", "png", "gif", "webp"] }
lol_html = "3.0.0"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tera = "1.20.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tower-http = { version = "0.6.6", features = ["fs"] }
url = "2.5.8"

[build-dependencies]
css-minify = "0.5.2"
