name: Check build

permissions:
  contents: read

on: pull_request

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check build
        run: cargo check --locked
