name: Check code formatting

permissions:
  contents: read

on: pull_request

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout txtdot
        uses: actions/checkout@v4

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        working-directory: txtdot
        run: cargo fmt --all -- --check
